"""Build a lightweight Python codegraph for repository navigation."""

from __future__ import annotations

import ast
import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

DEFAULT_INCLUDE_ROOTS = ("src", "tests", "scripts")
DEFAULT_OUTPUT_DIR = Path(".codex") / "codegraph"


@dataclass(frozen=True)
class ParsedModule:
    module_name: str
    relative_path: str
    symbols: list[dict[str, Any]]
    edges: list[dict[str, Any]]


def build_index(
    repo_root: Path,
    *,
    include_roots: tuple[str, ...] = DEFAULT_INCLUDE_ROOTS,
) -> dict[str, Any]:
    repo_root = repo_root.resolve()
    symbols: list[dict[str, Any]] = []
    edges: list[dict[str, Any]] = []
    files: list[str] = []
    parse_errors: list[dict[str, str]] = []

    for path in _iter_python_files(repo_root, include_roots):
        relative_path = path.relative_to(repo_root).as_posix()
        files.append(relative_path)
        try:
            parsed = _parse_module(repo_root, path)
        except SyntaxError as exc:
            parse_errors.append(
                {
                    "file": relative_path,
                    "message": str(exc),
                }
            )
            continue
        symbols.extend(parsed.symbols)
        edges.extend(parsed.edges)

    symbol_counts = Counter(symbol["symbol_type"] for symbol in symbols)
    edge_counts = Counter(edge["kind"] for edge in edges)

    return {
        "schema_version": 1,
        "repo_root": str(repo_root),
        "include_roots": list(include_roots),
        "files": sorted(files),
        "symbols": symbols,
        "edges": edges,
        "parse_errors": parse_errors,
        "stats": {
            "file_count": len(files),
            "symbol_count": len(symbols),
            "edge_count": len(edges),
            "symbol_types": dict(symbol_counts),
            "edge_kinds": dict(edge_counts),
        },
    }


def summarize_index(index: dict[str, Any]) -> str:
    symbols = index["symbols"]
    edges = index["edges"]
    files = index["files"]

    package_counts: Counter[str] = Counter()
    module_symbol_counts: Counter[str] = Counter()
    type_counts: Counter[str] = Counter(symbol["symbol_type"] for symbol in symbols)
    outbound_counts: Counter[str] = Counter(edge["source"] for edge in edges if edge["source"])

    for symbol in symbols:
        qualname = symbol["qualname"]
        if qualname.startswith("flowscribe.") and qualname.count(".") >= 1:
            package = qualname.split(".", 2)[1]
        else:
            package = qualname.split(".", 1)[0]
        package_counts[package] += 1
        if symbol["symbol_type"] != "module":
            module_symbol_counts[symbol["module"]] += 1

    lines = [
        "# FlowScribe Codegraph",
        "",
        "This file is generated by `python scripts/build_codegraph.py`.",
        "",
        "## Stats",
        "",
        f"- Files indexed: {len(files)}",
        f"- Symbols indexed: {len(symbols)}",
        f"- Edges indexed: {len(edges)}",
        f"- Symbol types: {json.dumps(type_counts, ensure_ascii=False, sort_keys=True)}",
        "",
        "## Top Packages",
        "",
    ]

    for package, count in package_counts.most_common(15):
        lines.append(f"- `{package}`: {count} symbols")

    lines.extend(
        [
            "",
            "## Top Modules By Symbol Count",
            "",
        ]
    )
    for module_name, count in module_symbol_counts.most_common(20):
        lines.append(f"- `{module_name}`: {count} symbols")

    lines.extend(
        [
            "",
            "## Highest-Connectivity Symbols",
            "",
        ]
    )
    for qualname, count in outbound_counts.most_common(20):
        lines.append(f"- `{qualname}`: {count} outgoing edges")

    lines.extend(
        [
            "",
            "## Recommended Queries",
            "",
            "- `python scripts/query_codegraph.py search TranscriptionService`",
            "- `python scripts/query_codegraph.py show flowscribe.app.service.TranscriptionService`",
            "- `python scripts/query_codegraph.py search QueueView --type class`",
            "- `python scripts/query_codegraph.py neighbors flowscribe.providers.transcribe.registry.ParaformerProvider`",
        ]
    )
    return "\n".join(lines) + "\n"


def _iter_python_files(repo_root: Path, include_roots: tuple[str, ...]) -> list[Path]:
    paths: list[Path] = []
    for root_name in include_roots:
        root_path = repo_root / root_name
        if not root_path.exists():
            continue
        for path in root_path.rglob("*.py"):
            if path.name.endswith(".py"):
                paths.append(path)
    return sorted(paths)


def _parse_module(repo_root: Path, path: Path) -> ParsedModule:
    source = path.read_text(encoding="utf-8-sig")
    tree = ast.parse(source, filename=str(path))
    relative_path = path.relative_to(repo_root).as_posix()
    module_name = _module_name_for_path(repo_root, path)
    builder = _ModuleGraphBuilder(module_name=module_name, relative_path=relative_path)
    return builder.build(tree)


def _module_name_for_path(repo_root: Path, path: Path) -> str:
    relative = path.relative_to(repo_root).with_suffix("")
    parts = list(relative.parts)
    if parts and parts[0] == "src":
        parts = parts[1:]
    return ".".join(parts)


class _ModuleGraphBuilder(ast.NodeVisitor):
    def __init__(self, *, module_name: str, relative_path: str) -> None:
        self.module_name = module_name
        self.relative_path = relative_path
        self.symbols: list[dict[str, Any]] = []
        self.edges: list[dict[str, Any]] = []
        self._scope_stack: list[str] = []

    def build(self, tree: ast.Module) -> ParsedModule:
        module_doc = _first_line(ast.get_docstring(tree))
        self.symbols.append(
            {
                "symbol_type": "module",
                "name": self.module_name.rsplit(".", 1)[-1],
                "qualname": self.module_name,
                "module": self.module_name,
                "file": self.relative_path,
                "line_start": 1,
                "line_end": max(1, getattr(tree, "end_lineno", 1)),
                "parent": None,
                "doc": module_doc,
                "bases": [],
                "args": [],
            }
        )
        self._record_import_edges(tree)
        self.visit(tree)
        return ParsedModule(
            module_name=self.module_name,
            relative_path=self.relative_path,
            symbols=self.symbols,
            edges=self.edges,
        )

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        qualname = self._qualname(node.name)
        bases = [_expr_name(base) for base in node.bases if _expr_name(base)]
        self.symbols.append(
            {
                "symbol_type": "class",
                "name": node.name,
                "qualname": qualname,
                "module": self.module_name,
                "file": self.relative_path,
                "line_start": node.lineno,
                "line_end": getattr(node, "end_lineno", node.lineno),
                "parent": self._scope_stack[-1] if self._scope_stack else self.module_name,
                "doc": _first_line(ast.get_docstring(node)),
                "bases": bases,
                "args": [],
            }
        )
        self._add_edge("contains", self._scope_stack[-1] if self._scope_stack else self.module_name, qualname)
        for base in bases:
            self._add_edge("inherits", qualname, base)
        self._scope_stack.append(qualname)
        self.generic_visit(node)
        self._scope_stack.pop()

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self._visit_function_like(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        self._visit_function_like(node)

    def _visit_function_like(self, node: ast.FunctionDef | ast.AsyncFunctionDef) -> None:
        parent = self._scope_stack[-1] if self._scope_stack else self.module_name
        symbol_type = "method" if self._scope_stack and self._is_class_scope(self._scope_stack[-1]) else "function"
        qualname = self._qualname(node.name)
        self.symbols.append(
            {
                "symbol_type": symbol_type,
                "name": node.name,
                "qualname": qualname,
                "module": self.module_name,
                "file": self.relative_path,
                "line_start": node.lineno,
                "line_end": getattr(node, "end_lineno", node.lineno),
                "parent": parent,
                "doc": _first_line(ast.get_docstring(node)),
                "bases": [],
                "args": [arg.arg for arg in node.args.args],
            }
        )
        self._add_edge("contains", parent, qualname)
        for target in _collect_call_targets(node):
            self._add_edge("calls", qualname, target)
        self._scope_stack.append(qualname)
        self.generic_visit(node)
        self._scope_stack.pop()

    def _record_import_edges(self, tree: ast.Module) -> None:
        for node in tree.body:
            if isinstance(node, ast.Import):
                for alias in node.names:
                    self._add_edge("imports", self.module_name, alias.name)
            elif isinstance(node, ast.ImportFrom):
                imported_module = _resolve_import_from(self.module_name, node)
                if imported_module:
                    self._add_edge("imports", self.module_name, imported_module)

    def _qualname(self, name: str) -> str:
        if not self._scope_stack:
            return f"{self.module_name}.{name}"
        return f"{self._scope_stack[-1]}.{name}"

    def _add_edge(self, kind: str, source: str, target: str) -> None:
        if not source or not target:
            return
        self.edges.append(
            {
                "kind": kind,
                "source": source,
                "target": target,
                "file": self.relative_path,
            }
        )

    @staticmethod
    def _is_class_scope(qualname: str) -> bool:
        return qualname.split(".")[-1][:1].isupper()


def _collect_call_targets(node: ast.AST) -> list[str]:
    targets: list[str] = []
    for child in ast.walk(node):
        if not isinstance(child, ast.Call):
            continue
        target = _expr_name(child.func)
        if target:
            targets.append(target)
    return targets


def _expr_name(node: ast.AST | None) -> str | None:
    if node is None:
        return None
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        left = _expr_name(node.value)
        if left:
            return f"{left}.{node.attr}"
        return node.attr
    if isinstance(node, ast.Subscript):
        return _expr_name(node.value)
    if isinstance(node, ast.Call):
        return _expr_name(node.func)
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def _resolve_import_from(module_name: str, node: ast.ImportFrom) -> str | None:
    base = node.module or ""
    if node.level == 0:
        return base

    module_parts = module_name.split(".")
    if node.level > len(module_parts):
        return base or None

    parent_parts = module_parts[:-node.level]
    if base:
        return ".".join([*parent_parts, base])
    return ".".join(parent_parts)


def _first_line(docstring: str | None) -> str:
    if not docstring:
        return ""
    return docstring.strip().splitlines()[0].strip()


def write_index_artifacts(
    repo_root: Path,
    *,
    include_roots: tuple[str, ...] = DEFAULT_INCLUDE_ROOTS,
    output_dir: Path = DEFAULT_OUTPUT_DIR,
) -> tuple[Path, Path, dict[str, Any]]:
    index = build_index(repo_root, include_roots=include_roots)
    resolved_output_dir = (repo_root / output_dir).resolve()
    resolved_output_dir.mkdir(parents=True, exist_ok=True)

    index_path = resolved_output_dir / "index.json"
    summary_path = resolved_output_dir / "summary.md"

    index_path.write_text(json.dumps(index, ensure_ascii=False, indent=2), encoding="utf-8")
    summary_path.write_text(summarize_index(index), encoding="utf-8")
    return index_path, summary_path, index
